// website/playground/components/VersionLink.vue
<script setup>
import { onMounted } from "vue";

const { version } = defineProps({
  version: {
    type: String,
    required: true,
  },
});

const match = version.match(/^pr-(\d+)$/);
let href;
if (match) {
  href = `pull/${match[1]}`;
} else if (/\.0$/.test(version)) {
  href = `releases/tag/${version}`;
} else {
  href = `blob/main/CHANGELOG.md#${version.replaceAll(".", "")}`;
}

const formattedVersion = match ? `PR #${match[1]}` : `v${version}`;

onMounted(() => {
  document.title = `Prettier ${formattedVersion}`;
});
</script>

<template>
  <a
    :href="`https://github.com/prettier/prettier/${href}`"
    target="_blank"
    rel="noreferrer noopener"
  >
    {{ formattedVersion }}
  </a>
</template>

// website/playground/VersionLink.jsx
export default function VersionLink({ version }) {
  const match = version.match(/^pr-(\d+)$/);
  let href;
  if (match) {
    href = `pull/${match[1]}`;
  } else if (/\.0$/.test(version)) {
    href = `releases/tag/${version}`;
  } else {
    href = `blob/main/CHANGELOG.md#${version.replaceAll(".", "")}`;
  }

  const formattedVersion = match ? `PR #${match[1]}` : `v${version}`;

  document.title = `Prettier ${formattedVersion}`;

  return (
    <a
      href={`https://github.com/prettier/prettier/${href}`}
      target="_blank"
      rel="noreferrer noopener"
    >
      {formattedVersion}
    </a>
  );
}
VersionLink.props = {
  version: { type: String, required: true },
};
