// website/playground/VersionLink.jsx
export default function VersionLink({ version }) {
  const match = version.match(/^pr-(\d+)$/);
  let href;
  if (match) {
    href = `pull/${match[1]}`;
  } else if (/\.0$/.test(version)) {
    href = `releases/tag/${version}`;
  } else {
    href = `blob/main/CHANGELOG.md#${version.replaceAll(".", "")}`;
  }

  const formattedVersion = match ? `PR #${match[1]}` : `v${version}`;

  document.title = `Prettier ${formattedVersion}`;

  return (
    <a
      href={`https://github.com/prettier/prettier/${href}`}
      target="_blank"
      rel="noreferrer noopener"
    >
      {formattedVersion}
    </a>
  );
}
VersionLink.props = {
  version: { type: String, required: true },
};

// website/playground/version-link.vue
<script setup>
import { computed, watch, onMounted } from "vue";
import { settings } from "./composables/playground-settings.js";

const props = defineProps({
  version: { type: String, required: true },
});

const versionLabel = computed(() => {
  const match = props.version.match(/^pr-(\d+)$/);
  return match ? `PR #${match[1]}` : `v${props.version}`;
});

const updateTitle = () => {
  document.title = `Prettier ${versionLabel.value}`;
};

function onReleaseChannelChange(event) {
  settings.releaseChannel = event.target.value;
}

watch(() => props.version, updateTitle);

onMounted(updateTitle);
</script>

<template>
  <span class="version-wrapper">
    <a
      class="version-link"
      :href="`https://github.com/prettier/prettier/releases/tag/${version}`"
      target="_blank"
      rel="noopener noreferrer"
    >
      {{ versionLabel }}
    </a>
    <select
      class="channel-select"
      :value="settings.releaseChannel"
      @click.stop
      @change="onReleaseChannelChange"
    >
      <option value="stable">stable</option>
      <option value="next">next</option>
    </select>
  </span>
</template>

<style>
.version-wrapper {
  display: flex;
}

.version-link {
  color: inherit;
  text-decoration: none;
  line-height: 0;
  opacity: 0.5;
}
</style>
