// website/playground/components/ThemeToggle.vue
<script setup>
import { theme, toggleTheme } from "../composables/theme.js";
import DarkIcon from "./icons/DarkIcon.vue";
import LightIcon from "./icons/LightIcon.vue";
import Button from "./ui/Button.vue";
</script>

<template>
  <Button @click="toggleTheme" icon>
    <DarkIcon v-if="theme === 'dark'" />
    <LightIcon v-else />
  </Button>
</template>

// website/playground/components/ThemeToggle.jsx
import { theme, toggleTheme } from "../composables/theme.js";
import { DarkIcon, LightIcon } from "./Icons.jsx";
import Button from "./ui/Button.jsx";

export default function ThemeToggle() {
  return (
    <Button
      onClick={toggleTheme}
      icon
      aria-label={`Switch to ${theme.value === "dark" ? "light" : "dark"} theme`}
    >
      {theme.value === "dark" ? <DarkIcon /> : <LightIcon />}
    </Button>
  );
}
