// website/playground/sidebar/SidebarOptions.jsx
import { SidebarCategory } from "./components.jsx";
import Option from "./options.jsx";

// Copied from `/src/cli/utilities.js`
function groupBy(array, iteratee) {
  const result = Object.create(null);

  for (const value of array) {
    const key = iteratee(value);

    if (Array.isArray(result[key])) {
      result[key].push(value);
    } else {
      result[key] = [value];
    }
  }

  return result;
}

export default {
  name: "SidebarOptions",
  props: {
    categories: { type: Array, required: true },
    availableOptions: { type: Array, required: true },
    optionValues: { type: Object, required: true },
  },
  emits: ["option-value-change"],
  setup(props, { emit }) {
    return () => {
      const options = groupBy(props.availableOptions, (option) => option.category);
      return props.categories.map((category) =>
        options[category] ? (
          <SidebarCategory key={category} title={category}>
            {options[category].map((option) => (
              <Option
                key={option.name}
                option={option}
                value={props.optionValues[option.name]}
                onChange={(option, val) => emit("option-value-change", option, val)}
              />
            ))}
          </SidebarCategory>
        ) : null,
      );
    };
  },
};

// website/playground/components/sidebar/SidebarOptions.vue
<script setup>
import Collapsible from "../ui/Collapsible.vue";
import Option from "./Options.vue";

const props = defineProps({
  categories: {
    type: Array,
    required: true,
  },
  availableOptions: { type: Array, required: true },
  optionValues: { type: Object, required: true },
});

defineEmits(["option-value-change"]);

const options = groupBy(props.availableOptions, (option) => option.category);

function groupBy(array, iteratee) {
  const result = Object.create(null);

  for (const value of array) {
    const key = iteratee(value);

    if (Array.isArray(result[key])) {
      result[key].push(value);
    } else {
      result[key] = [value];
    }
  }

  return result;
}
</script>

<template>
  <Collapsible v-for="category in categories" :key="category" :title="category">
    <Option
      v-for="option in options[category]"
      :key="option.name"
      :option="option"
      :value="optionValues[option.name]"
      @change="(option, value) => $emit('option-value-change', option, value)"
    />
  </Collapsible>
</template>
