// website/playground/components/sidebar/SidebarOptions.jsx
import Option from "./Options.jsx";
import SidebarCategory from "./SidebarCategory.jsx";

// Copied from `/src/cli/utilities.js`
function groupBy(array, iteratee) {
  const result = Object.create(null);

  for (const value of array) {
    const key = iteratee(value);

    if (Array.isArray(result[key])) {
      result[key].push(value);
    } else {
      result[key] = [value];
    }
  }

  return result;
}

export default function SidebarOptions(
  { categories, availableOptions, optionValues },
  { emit },
) {
  const onOptionValueChange = (option, value) =>
    emit("option-value-change", option, value);
  const options = groupBy(availableOptions, (option) => option.category);
  return categories.map((category) =>
    options[category] ? (
      <SidebarCategory key={category} title={category}>
        {options[category].map((option) => (
          <Option
            key={option.name}
            option={option}
            value={optionValues[option.name]}
            onChange={onOptionValueChange}
          />
        ))}
      </SidebarCategory>
    ) : null,
  );
}
SidebarOptions.props = {
  categories: { type: Array, required: true },
  availableOptions: { type: Array, required: true },
  optionValues: { type: Object, required: true },
};
SidebarOptions.emits = ["option-value-change"];

// website/playground/components/sidebar/SidebarOptions.vue
<script setup>
import Collapsible from "../ui/Collapsible.vue";
import Option from "./Options.vue";

const props = defineProps({
  categories: {
    type: Array,
    required: true,
  },
  availableOptions: { type: Array, required: true },
  optionValues: { type: Object, required: true },
});

defineEmits(["option-value-change"]);

const options = groupBy(props.availableOptions, (option) => option.category);

function groupBy(array, iteratee) {
  const result = Object.create(null);

  for (const value of array) {
    const key = iteratee(value);

    if (Array.isArray(result[key])) {
      result[key].push(value);
    } else {
      result[key] = [value];
    }
  }

  return result;
}
</script>

<template>
  <Collapsible v-for="category in categories" :key="category" :title="category">
    <Option
      v-for="option in options[category]"
      :key="option.name"
      :option="option"
      :value="optionValues[option.name]"
      @change="(option, value) => $emit('option-value-change', option, value)"
    />
  </Collapsible>
</template>
